### ISSUE TITLE
inners

### ISSUE THREAD

**Issue by 75lb** [Oakleon/oakdatastore#1]
not really an issue, but noticed all your exported methods are showing as "inner" scope.. assume it's because you are generating docs from compiled JS, they should all show as "static" scope.. and now i see why, coz you're using ES7.. if you remove the `async` and `await` keywords from the source it will document directly using jsdoc2md, and show the correct scopes.. anyhoo.. that's all ;)

**Comment by chrishiestand** [comment]
Ah, yes. Thanks for pointing this problem out. It's a little bit of a tricky situation since async/await isn't officially adopted yet and may never be <https://twitter.com/bterlson/status/692489384654999552>. So jsdoc2md fails to parse src/index.js and so we have to parse build/index.js which isn't easy to parse. I wonder if the parser could be easily modified to read the build version? Maybe it's not worth pursuing? Or maybe I should do a little shell hack to get the src to be readable? That would be the quickest fix... I think I'll do that.
